kind: Deployment
apiVersion: apps/v1
metadata:
  name: kliqr-user
  labels:
    app: kliqr-assessment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kliqr-assessment
  template:
    metadata:
      labels:
        app: kliqr-assessment
    spec:
      containers:
        - name: kliqr-user-service-deployment
          image: famuyiwa/kliqr-user:v1
          ports:
            - containerPort: 3219
          env:
            - name: PORT
              value: 3219
---
kind: Service
apiVersion: v1
metadata:
  name: kliqr-user-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: kliqr-assessment
  ports:
    - name: kliqr-user-port
      protocol: TCP
      port: 3219
